###
# Find All Users
GET {{ baseURL }}/users

###
# Find User By Id
GET {{ baseURL }}/users/331b3649-c113-4388-baf8-c9130cbdee27

###
# Create User
POST {{ baseURL }}/users
Content-Type: application/json

{
  "email": "example2@email.com",
  "password": "password",
  "role": "USER"
}

###
# Modify User By Id
PUT {{ baseURL }}/users/059ea3ca-b08a-44f7-9408-879c35410ce9
Content-Type: application/json

{
  "email": "example12@email.com",
  "password": "password",
  "role": "USER"
}

###
# Delete User By Id
DELETE {{ baseURL }}/users/059ea3ca-b08a-44f7-9408-879c35410ce9
